name: CinePrev
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+3
  carousel_slider: ^1.4.1
  dots_indicator: ^1.0.0
  sqflite: ^1.3.0
  path_provider: ^1.1.2
  flutter_cache_manager: ^1.4.1
  cache_image: ^1.0.5
  ext_storage: ^1.0.3
  dio: any
  permission_handler: '^4.3.0' 
  flutter_downloader: ^1.3.1
  achievement_view: ^0.2.0
  crypto_font_icons: ^0.1.0+1
  flutter_typeahead: ^1.8.0
  connectivity: ^0.4.8+2
  fluttertoast: ^4.0.1
  youtube_player_flutter: ^6.1.0+7
  url_launcher: ^5.4.10
  firebase_admob: ^0.9.3+2
  firebase_storage: any
  facebook_audience_network: ^0.5.0
  adcolony: ^2.0.4
  applovin: ^1.0.3
  onesignal_flutter: ^2.0.0
  flutter_spinkit: "^4.1.2"
  
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gif/loading.gif 
    - assets/logo.png
    - assets/instagram.png
    - assets/nocover.jpg
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway-SemiBold
      fonts:
        # - asset: assets/font/Raleway-Bold.ttf
        - asset: assets/font/Raleway-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
